### PR TITLE
Fix: loading failed for local openapi json file on Windows

### LINKED ISSUE #190: Loading failed for local openapi json file
When I update my project from the old version "0.4.0" to the latest version "0.6.0", I can't start the project.
Below is a screenshot of the error.

<details>
<summary>screenshot</summary>

图片
</details>

## How to reproduce
I started from the template one
```
npx create-docusaurus-openapi docusaurus-openapi-example
```
Then update the package
```
yarn upgrade docusaurus-preset-openapi --latest
```
Also, add `url` for fixing url issue
```
yarn add url
```
Then, I start the project
```
cd docusaurus-openapi-example
yarn start
```
Check the above screenshot.

The following is my package.json
<details>
<summary>package.json</summary>

```
{
  "name": "docusaurus-openapi-example",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@docusaurus/core": "2.0.0-beta.21",
    "@mdx-js/react": "^1.6.21",
    "clsx": "^1.1.1",
    "docusaurus-preset-openapi": "0.6.0",
    "prism-react-renderer": "^1.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "url": "^0.11.0"
  },
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids"
  },
  "browserslist": {
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```
</details>

## Comment
Please let me know if I make any mistakes in the initialization of the project.

PS: Maybe the template example also needs a version update💖

### PR DESCRIPTION
**Pull request by yzhe819**
**Close #190** 

Use regex to check if it's an external link instead of using the URL and try/catch.
It can support **Windows** platforms..

### CODE REVIEW

**Comment by yzhe819** [comment]
@bourdakos1 ready for review

File: packages/docusaurus-plugin-openapi/src/util.ts [hunk 1]
```diff
@@ -6,10 +6,5 @@
  * ========================================================================== */
 
 export const isURL = (url: string) => {
-  try {
-    new URL(url);
-    return true;
-  } catch (e) {
-    return false;
-  }
+  return /^(?:[a-z]+:)?\/\//i.test(url);
```
Comment (bourdakos1) [inline packages/docusaurus-plugin-openapi/src/util.ts:9]: Could you write some test cases to cover this? Especially a test case for the urls/paths that were causing the issue

**Review by bourdakos1 — CHANGES_REQUESTED** [review]

**Comment by yzhe819** [comment]
@bourdakos1 For the header section, do I use a generic cloud annotations header like other files?

**Review by bourdakos1 — APPROVED** [review]
