### PR TITLE
fix: compatability with docusaurus 2.2.0

### LINKED ISSUE #222: Error when running with Docusaurus v2.2.0
Hi

Upgrading to Docusaurus v2.2.0 I get this:

```bash
❯ npm run build

> flagsmith-docs@0.0.0 build
> docusaurus build

[INFO] [en] Creating an optimized production build...
WARNING: Loading a directory of OpenAPI definitions is experimental and subject to unannounced breaking changes.

● Client █████████████████████████ building (11%) 0/1 entries 708/737 dependencies 105/303 modules 74 active
 babel-loader › mdx-loader › docs/guides-and-examples/testing-push-notifications.md

● Server █████████████████████████ building (11%) 0/1 entries 881/947 dependencies 166/413 modules 120 active
 babel-loader › mdx-loader › docs/clients/client-side/android.md

[ERROR] TypeError: Cannot read properties of undefined (reading 'mermaid')
    at Object.mdxLoader (/Users/ben/flagsmith/docs/node_modules/@docusaurus/mdx-loader/lib/loader.js:115:43)
    at LOADER_EXECUTION (/Users/ben/flagsmith/docs/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
    at runSyncOrAsync (/Users/ben/flagsmith/docs/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
    at iterateNormalLoaders (/Users/ben/flagsmith/docs/node_modules/loader-runner/lib/LoaderRunner.js:250:2)
    at /Users/ben/flagsmith/docs/node_modules/loader-runner/lib/LoaderRunner.js:223:4
    at /Users/ben/flagsmith/docs/node_modules/webpack/lib/NormalModule.js:834:15
    at eval (eval at create (/Users/ben/flagsmith/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
[INFO] Docusaurus version: 2.2.0
Node version: v16.15.1
```

The PR we have on this if you want to reproduce is here: https://github.com/Flagsmith/flagsmith-docs/pull/221

### PR DESCRIPTION
**Pull request by sean-perkins**
Adds new property option that was introduced in v2.2.0 of `@docusaurus/mdx-loader`. 

Resolves #222

Related Docusaurus issue: https://github.com/facebook/docusaurus/issues/8298

### CODE REVIEW

**Review by bourdakos1 — APPROVED** [review]

**Comment by sean-perkins** [comment]
Thanks for the quick review 🙂 note for future context, we could probably update the `@docusaurus/types` to `^2.2.0` and then deconstruct/pass the `markdownConfig` from the plugin options to this and fallback to `{}` if unset. 

But this fix unblocks the 2.2.0 support for now until we gather more use cases for that change.

**Comment by dabeeeenster** [comment]
Thanks so much!

File: packages/docusaurus-plugin-openapi/src/index.ts [hunk 1]
```diff
@@ -274,6 +274,8 @@ export default function pluginOpenAPI(
                     rehypePlugins,
                     beforeDefaultRehypePlugins,
                     beforeDefaultRemarkPlugins,
+                    // Docusaurus 2.2.0 has a regression that requires this option to be set.
+                    markdownConfig: {},
```
Comment (slorber) [inline packages/docusaurus-plugin-openapi/src/index.ts:278]: I would rather pass `markdownConfig: context.siteConfig.markdown`: this is what all other plugins do, and third-party plugin authors using our mdx loader should rather do the same to apply global markdown config for all md docs. There will be more Markdown site options in the future
